import i18n from "@/libs/i18n";

export const $countries = [
	{ label: i18n.t("Saudi Arabia"), value: "Saudi Arabia" },
	{ label: i18n.t("Afghanistan"), value: "Afghanistan" },
	{ label: i18n.t("Albania"), value: "Albania" },
	{ label: i18n.t("Algeria"), value: "Algeria" },
	{ label: i18n.t("Andorra"), value: "Andorra" },
	{ label: i18n.t("Angola"), value: "Angola" },
	{ label: i18n.t("Armenia"), value: "Armenia" },
	{ label: i18n.t("Azerbaijan"), value: "Azerbaijan" },
	{ label: i18n.t("Bahamas"), value: "Bahamas" },
	{ label: i18n.t("Bahrain"), value: "Bahrain" },
	{ label: i18n.t("Bangladesh"), value: "Bangladesh" },
	{ label: i18n.t("Belarus"), value: "Belarus" },
	{ label: i18n.t("Bolivia"), value: "Bolivia" },
	{ label: i18n.t("Botswana"), value: "Botswana" },
	{ label: i18n.t("Cameroon"), value: "Cameroon" },
	{ label: i18n.t("Congo"), value: "Congo" },
	{ label: i18n.t("Cuba"), value: "Cuba" },
	{ label: i18n.t("Cyprus"), value: "Cyprus" },
	{ label: i18n.t("Egypt"), value: "Egypt" },
	{ label: i18n.t("Gabon"), value: "Gabon" },
	{ label: i18n.t("Gambia"), value: "Gambia" },
	{ label: i18n.t("Georgia"), value: "Georgia" },
	{ label: i18n.t("Ghana"), value: "Ghana" },
	{ label: i18n.t("Greenland"), value: "Greenland" },
	{ label: i18n.t("Guinea"), value: "Guinea" },
	{ label: i18n.t("Honduras"), value: "Honduras" },
	{ label: i18n.t("Iraq"), value: "Iraq" },
	{ label: i18n.t("Jamaica"), value: "Jamaica" },
	{ label: i18n.t("Kuwait"), value: "Kuwait" },
	{ label: i18n.t("Lebanon"), value: "Lebanon" },
	{ label: i18n.t("Libya"), value: "Libya" },
	{ label: i18n.t("Morocco"), value: "Morocco" },
	{ label: i18n.t("Mozambique"), value: "Mozambique" },
	{ label: i18n.t("Myanmar"), value: "Myanmar" },
	{ label: i18n.t("Namibia"), value: "Namibia" },
	{ label: i18n.t("Nepal"), value: "Nepal" },
	{ label: i18n.t("Nicaragua"), value: "Nicaragua" },
	{ label: i18n.t("Oman"), value: "Oman" },
	{ label: i18n.t("Palestine"), value: "Palestine" },
	{ label: i18n.t("Senegal"), value: "Senegal" },
	{ label: i18n.t("Sudan"), value: "Sudan" },
	{ label: i18n.t("Tunisia"), value: "Tunisia" },
	{ label: i18n.t("United Arab Emirates"), value: "United Arab Emirates" },
];

export const $cities = {
	"Saudi Arabia": [
		{ label: i18n.t("Jubail"), value: "Jubail" },
		{ label: i18n.t("Buraidah"), value: "Buraidah" },
		{ label: i18n.t("Riyadh"), value: "Riyadh" },
		{ label: i18n.t("Mecca"), value: "Mecca" },
		{ label: i18n.t("Medina"), value: "Medina" },
		{ label: i18n.t("Tabuk"), value: "Tabuk" },
		{ label: i18n.t("Dammam"), value: "Dammam" },
		{ label: i18n.t("Al Taeif"), value: "Al Taeif" },
		{ label: i18n.t("Al Ahsaa"), value: "Al Ahsaa" },
		{ label: i18n.t("Al Qatif"), value: "Al Qatif" },
		{ label: i18n.t("Najran"), value: "Najran" },
		{ label: i18n.t("Hafr Albatin"), value: "Hafr Albatin" },
		{ label: i18n.t("Dabaa"), value: "Dabaa" },
		{ label: i18n.t("Al Kharaj"), value: "Al Kharaj" },
		{ label: i18n.t("Yanbu`"), value: "Yanbu" },
		{ label: i18n.t("Khobar"), value: "Khobar" },
		{ label: i18n.t("A'ror"), value: "A'ror" },
		{ label: i18n.t("Sakaka"), value: "Sakaka" },
		{ label: i18n.t("Jizan"), value: "Jizan" },
		{ label: i18n.t("Al Qarrayat"), value: "Al Qarrayat" },
		{ label: i18n.t("Al Zahran"), value: "Al Zahran" },
		{ label: i18n.t("Al Zelafa"), value: "Al Zelafa" },
		{ label: i18n.t("Al Bahah"), value: "Al Bahah" },
		{ label: i18n.t("Al Rass"), value: "Al Rass" },
		{ label: i18n.t("Besha"), value: "Besha" },
		{ label: i18n.t("Sehat"), value: "Sehat" },
		{ label: i18n.t("Sharora"), value: "Sharora" },
		{ label: i18n.t("Bahra"), value: "Bahra" },
		{ label: i18n.t("Afif"), value: "Afif" },
		{ label: i18n.t("Sabia"), value: "Sabia" },
		{ label: i18n.t("Bariq"), value: "Bariq" },
		{ label: i18n.t("Al Aflaj"), value: "Al Aflaj" },
		{ label: i18n.t("Al Bakiria"), value: "Al Bakiria" },
		{ label: i18n.t("Al Moznab"), value: "Al Moznab" },
		{ label: i18n.t("Al Bada'e"), value: "Al Bada'e" },
		{ label: i18n.t("Riyadh Al Khabraa"), value: "Riyadh Al Khabraa" },
		{ label: i18n.t("Abha"), value: "Abha" },
		{ label: i18n.t("Khamees Masheet"), value: "Khamees Masheet" },
		{ label: i18n.t("Mahayel Aseer"), value: "Mahayel Aseer" },
		{ label: i18n.t("Al A'laya"), value: "Al A'laya" },
		{ label: i18n.t("Aneeza"), value: "Aneeza" },
		{ label: i18n.t("Al Namaas"), value: "Al Namaas" },
		{ label: i18n.t("Jeddah"), value: "Jeddah" },
	],
	Afghanistan: [
		{ label: i18n.t("Herat"), value: "Herat" },
		{ label: i18n.t("Kabul"), value: "Kabul" },
		{ label: i18n.t("Kandahar"), value: "Kandahar" },
		{ label: i18n.t("Molah"), value: "Molah" },
		{ label: i18n.t("Rana"), value: "Rana" },
		{ label: i18n.t("Shar"), value: "Shar" },
		{ label: i18n.t("Sharif"), value: "Sharif" },
		{ label: i18n.t("Wazir Akbar Khan"), value: "Wazir Akbar Khan" },
	],
	Albania: [
		{ label: i18n.t("Elbasan"), value: "Elbasan" },
		{ label: i18n.t("Petran"), value: "Petran" },
		{ label: i18n.t("Pogradec"), value: "Pogradec" },
		{ label: i18n.t("Shkoder"), value: "Shkoder" },
		{ label: i18n.t("Tirana"), value: "Tirana" },
		{ label: i18n.t("Ura Vajgurore"), value: "Ura Vajgurore" },
	],
	Algeria: [
		{ label: i18n.t("Algiers"), value: "Algiers" },
		{ label: i18n.t("Annaba"), value: "Annaba" },
		{ label: i18n.t("Azazga"), value: "Azazga" },
		{ label: i18n.t("Blida"), value: "Blida" },
		{ label: i18n.t("Bordj"), value: "Bordj" },
		{ label: i18n.t("Bougara"), value: "Bougara" },
		{ label: i18n.t("Cheraga"), value: "Cheraga" },
		{ label: i18n.t("Chlef"), value: "Chlef" },
		{ label: i18n.t("Constantine"), value: "Constantine" },
		{ label: i18n.t("Djelfa"), value: "Djelfa" },
		{ label: i18n.t("Draria"), value: "Draria" },
		{ label: i18n.t("Illizi"), value: "Illizi" },
		{ label: i18n.t("Jijel"), value: "Jijel" },
		{ label: i18n.t("Kouba"), value: "Kouba" },
		{ label: i18n.t("Laghouat"), value: "Laghouat" },
		{ label: i18n.t("Oran"), value: "Oran" },
		{ label: i18n.t("Ouargla"), value: "Ouargla" },
		{ label: i18n.t("Relizane"), value: "Relizane" },
		{ label: i18n.t("Rouiba"), value: "Rouiba" },
		{ label: i18n.t("Saida"), value: "Saida" },
		{ label: i18n.t("Tamanghasset"), value: "Tamanghasset" },
		{ label: i18n.t("Tiaret"), value: "Tiaret" },
		{ label: i18n.t("Tissemsilt"), value: "Tissemsilt" },
		{ label: i18n.t("Tizi"), value: "Tizi" },
		{ label: i18n.t("Tlemcen"), value: "Tlemcen" },
	],
	Andorra: [
		{ label: i18n.t("Canillo"), value: "Canillo" },
		{ label: i18n.t("Encamp"), value: "Encamp" },
		{ label: i18n.t("Engordany"), value: "Engordany" },
		{ label: i18n.t("Llorts"), value: "Llorts" },
		{ label: i18n.t("Ordino"), value: "Ordino" },
		{ label: i18n.t("Sispony"), value: "Sispony" },
		{ label: i18n.t("Soldeu"), value: "Soldeu" },
	],
	Angola: [
		{ label: i18n.t("Ambriz"), value: "Ambriz" },
		{ label: i18n.t("Benguela"), value: "Benguela" },
		{ label: i18n.t("Cabinda"), value: "Cabinda" },
		{ label: i18n.t("Cacole"), value: "Cacole" },
		{ label: i18n.t("Camabatela"), value: "Camabatela" },
		{ label: i18n.t("Cazeta"), value: "Cazeta" },
		{ label: i18n.t("Huambo"), value: "Huambo" },
		{ label: i18n.t("Kuito"), value: "Kuito" },
		{ label: i18n.t("Lobito"), value: "Lobito" },
		{ label: i18n.t("Luanda"), value: "Luanda" },
		{ label: i18n.t("Lubango"), value: "Lubango" },
		{ label: i18n.t("Lucapa"), value: "Lucapa" },
		{ label: i18n.t("Lumeje"), value: "Lumeje" },
		{ label: i18n.t("Malanje"), value: "Malanje" },
		{ label: i18n.t("Menongue"), value: "Menongue" },
		{ label: i18n.t("Muxaluando"), value: "Muxaluando" },
		{ label: i18n.t("Namibe"), value: "Namibe" },
		{ label: i18n.t("Ondjiva"), value: "Ondjiva" },
		{ label: i18n.t("Piri"), value: "Piri" },
		{ label: i18n.t("Saurimo"), value: "Saurimo" },
		{ label: i18n.t("Talatona"), value: "Talatona" },
	],
	Armenia: [
		{ label: i18n.t("Abovyan"), value: "Abovyan" },
		{ label: i18n.t("Agarak"), value: "Agarak" },
		{ label: i18n.t("Apaga"), value: "Apaga" },
		{ label: i18n.t("Aparan"), value: "Aparan" },
		{ label: i18n.t("Arabkir"), value: "Arabkir" },
		{ label: i18n.t("Ashtarak"), value: "Ashtarak" },
		{ label: i18n.t("Hrazdan"), value: "Hrazdan" },
		{ label: i18n.t("Ijevan"), value: "Ijevan" },
		{ label: i18n.t("Jermuk"), value: "Jermuk" },
		{ label: i18n.t("Kapan"), value: "Kapan" },
		{ label: i18n.t("Tsaghkadzor"), value: "Tsaghkadzor" },
		{ label: i18n.t("Vanadzor"), value: "Vanadzor" },
		{ label: i18n.t("Yerevan"), value: "Yerevan" },
	],
	Azerbaijan: [
		{ label: i18n.t("Baku"), value: "Baku" },
		{ label: i18n.t("Nakhchivan"), value: "Nakhchivan" },
		{ label: i18n.t("Quba"), value: "Quba" },
		{ label: i18n.t("Qusar"), value: "Qusar" },
		{ label: i18n.t("Sulutapa"), value: "Sulutapa" },
		{ label: i18n.t("Sumqayit"), value: "Sumqayit" },
		{ label: i18n.t("Xirdalan"), value: "Xirdalan" },
		{ label: i18n.t("Zurges"), value: "Zurges" },
	],
	Bahamas: [
		{ label: i18n.t("Freeport"), value: "Freeport" },
		{ label: i18n.t("Nassau"), value: "Nassau" },
	],
	Bahrain: [
		{ label: i18n.t("Al Budayyi`"), value: "Al Budayyi`" },
		{ label: i18n.t("Al Hadd"), value: "Al Hadd" },
		{ label: i18n.t("Al Hamalah"), value: "Al Hamalah" },
		{ label: i18n.t("Al Janabiyah"), value: "Al Janabiyah" },
		{ label: i18n.t("Al Markh"), value: "Al Markh" },
		{ label: i18n.t("Al Muharraq"), value: "Al Muharraq" },
		{ label: i18n.t("Bani Jamrah"), value: "Bani Jamrah" },
		{ label: i18n.t("Barbar"), value: "Barbar" },
		{ label: i18n.t("Jurdab"), value: "Jurdab" },
		{ label: i18n.t("Madinat `Isa"), value: "Madinat `Isa" },
		{ label: i18n.t("Madinat Hamad"), value: "Madinat Hamad" },
		{ label: i18n.t("Manama"), value: "Manama" },
		{ label: i18n.t("Oil City"), value: "Oil City" },
		{ label: i18n.t("Sanabis"), value: "Sanabis" },
		{ label: i18n.t("Sanad"), value: "Sanad" },
		{ label: i18n.t("Sitrah"), value: "Sitrah" },
		{ label: i18n.t("Tubli"), value: "Tubli" },
	],
	Bangladesh: [
		{ label: i18n.t("Agrabad"), value: "Agrabad" },
		{ label: i18n.t("Bangla"), value: "Bangla" },
		{ label: i18n.t("Barisal"), value: "Barisal" },
		{ label: i18n.t("Bazar"), value: "Bazar" },
		{ label: i18n.t("Chittagong"), value: "Chittagong" },
		{ label: i18n.t("Comilla"), value: "Comilla" },
		{ label: i18n.t("Delta"), value: "Delta" },
		{ label: i18n.t("Dhaka"), value: "Dhaka" },
		{ label: i18n.t("Hossain"), value: "Hossain" },
		{ label: i18n.t("Jessore"), value: "Jessore" },
		{ label: i18n.t("Kabi"), value: "Kabi" },
		{ label: i18n.t("Kazipur"), value: "Kazipur" },
		{ label: i18n.t("Mymensingh"), value: "Mymensingh" },
		{ label: i18n.t("Narayanganj"), value: "Narayanganj" },
		{ label: i18n.t("Rajshahi"), value: "Rajshahi" },
		{ label: i18n.t("Tejgaon"), value: "Tejgaon" },
		{ label: i18n.t("Uttara"), value: "Uttara" },
	],
	Belarus: [
		{ label: i18n.t("Baranovichi"), value: "Baranovichi" },
		{ label: i18n.t("Borisov"), value: "Borisov" },
		{ label: i18n.t("Brest"), value: "Brest" },
		{ label: i18n.t("Dzyarzhynsk"), value: "Dzyarzhynsk" },
		{ label: i18n.t("Horki"), value: "Horki" },
		{ label: i18n.t("Hrodna"), value: "Hrodna" },
		{ label: i18n.t("Lahoysk"), value: "Lahoysk" },
		{ label: i18n.t("Lida"), value: "Lida" },
		{ label: i18n.t("Lyakhovichi"), value: "Lyakhovichi" },
		{ label: i18n.t("Lyaskavichy"), value: "Lyaskavichy" },
		{ label: i18n.t("Mazyr"), value: "Mazyr" },
		{ label: i18n.t("Minsk"), value: "Minsk" },
		{ label: i18n.t("Mogilev"), value: "Mogilev" },
		{ label: i18n.t("Navapolatsk"), value: "Navapolatsk" },
		{ label: i18n.t("Orsha"), value: "Orsha" },
		{ label: i18n.t("Pinsk"), value: "Pinsk" },
		{ label: i18n.t("Polatsk"), value: "Polatsk" },
		{ label: i18n.t("Radoshkovichi"), value: "Radoshkovichi" },
		{ label: i18n.t("Shklow"), value: "Shklow" },
		{ label: i18n.t("Vitebsk"), value: "Vitebsk" },
		{ label: i18n.t("Zaslawye"), value: "Zaslawye" },
		{ label: i18n.t("Zhodzina"), value: "Zhodzina" },
	],
	Bolivia: [
		{ label: i18n.t("Anillo"), value: "Anillo" },
		{ label: i18n.t("Aroma"), value: "Aroma" },
		{ label: i18n.t("Bermejo"), value: "Bermejo" },
		{ label: i18n.t("Caracasa"), value: "Caracasa" },
		{ label: i18n.t("Cobija"), value: "Cobija" },
		{ label: i18n.t("Cochabamba"), value: "Cochabamba" },
		{ label: i18n.t("Cotoca"), value: "Cotoca" },
		{ label: i18n.t("Cruz"), value: "Cruz" },
		{ label: i18n.t("Guayaramerin"), value: "Guayaramerin" },
		{ label: i18n.t("Oruro"), value: "Oruro" },
		{ label: i18n.t("Riberalta"), value: "Riberalta" },
		{ label: i18n.t("Sucre"), value: "Sucre" },
		{ label: i18n.t("Tarija"), value: "Tarija" },
		{ label: i18n.t("Trinidad"), value: "Trinidad" },
	],
	Botswana: [
		{ label: i18n.t("Francistown"), value: "Francistown" },
		{ label: i18n.t("Gaborone"), value: "Gaborone" },
		{ label: i18n.t("Orapa"), value: "Orapa" },
		{ label: i18n.t("Serowe"), value: "Serowe" },
		{ label: i18n.t("Village"), value: "Village" },
	],
	Cameroon: [
		{ label: i18n.t("Bafia"), value: "Bafia" },
		{ label: i18n.t("Bafoussam"), value: "Bafoussam" },
		{ label: i18n.t("Bamenda"), value: "Bamenda" },
		{ label: i18n.t("Buea"), value: "Buea" },
		{ label: i18n.t("Douala"), value: "Douala" },
		{ label: i18n.t("Kribi"), value: "Kribi" },
		{ label: i18n.t("Kumba"), value: "Kumba" },
		{ label: i18n.t("Ringo"), value: "Ringo" },
		{ label: i18n.t("Tibati"), value: "Tibati" },
	],
	Congo: [
		{ label: i18n.t("Banana"), value: "Banana" },
		{ label: i18n.t("Goma"), value: "Goma" },
		{ label: i18n.t("Kinshasa"), value: "Kinshasa" },
		{ label: i18n.t("Likasi"), value: "Likasi" },
		{ label: i18n.t("Lubumbashi"), value: "Lubumbashi" },
	],
	Cuba: [
		{ label: i18n.t("Bayamo"), value: "Bayamo" },
		{ label: i18n.t("Cienfuegos"), value: "Cienfuegos" },
		{ label: i18n.t("Habana"), value: "Habana" },
		{ label: i18n.t("Havana"), value: "Havana" },
		{ label: i18n.t("Matanzas"), value: "Matanzas" },
		{ label: i18n.t("Varadero"), value: "Varadero" },
		{ label: i18n.t("Villa"), value: "Villa" },
	],
	Cyprus: [
		{ label: i18n.t("Aradippou"), value: "Aradippou" },
		{ label: i18n.t("Chlorakas"), value: "Chlorakas" },
		{ label: i18n.t("Deryneia"), value: "Deryneia" },
		{ label: i18n.t("Famagusta"), value: "Famagusta" },
		{ label: i18n.t("Geroskipou"), value: "Geroskipou" },
		{ label: i18n.t("Kiti"), value: "Kiti" },
		{ label: i18n.t("Kyrenia"), value: "Kyrenia" },
		{ label: i18n.t("Larnaca"), value: "Larnaca" },
		{ label: i18n.t("Laxia"), value: "Laxia" },
		{ label: i18n.t("Limassol"), value: "Limassol" },
		{ label: i18n.t("Livadia"), value: "Livadia" },
		{ label: i18n.t("Morfou"), value: "Morfou" },
		{ label: i18n.t("Mouttagiaka"), value: "Mouttagiaka" },
		{ label: i18n.t("Nicosia"), value: "Nicosia" },
		{ label: i18n.t("Paphos"), value: "Paphos" },
		{ label: i18n.t("Paralimni"), value: "Paralimni" },
		{ label: i18n.t("Parekklisha"), value: "Parekklisha" },
		{ label: i18n.t("Prodromi"), value: "Prodromi" },
		{ label: i18n.t("Sotira"), value: "Sotira" },
		{ label: i18n.t("Strovolos"), value: "Strovolos" },
		{ label: i18n.t("Tera"), value: "Tera" },
	],
	Egypt: [
		{ label: i18n.t("Al Mahallah al Kubra"), value: "Al Mahallah al Kubra" },
		{ label: i18n.t("Al Mansurah"), value: "Al Mansurah" },
		{ label: i18n.t("Alexandria"), value: "Alexandria" },
		{ label: i18n.t("Assiut"), value: "Assiut" },
		{ label: i18n.t("Bani Suwayf"), value: "Bani Suwayf" },
		{ label: i18n.t("Cairo"), value: "Cairo" },
		{ label: i18n.t("Damietta"), value: "Damietta" },
		{ label: i18n.t("Giza"), value: "Giza" },
		{ label: i18n.t("Ismailia"), value: "Ismailia" },
		{ label: i18n.t("Kafr ash Shaykh"), value: "Kafr ash Shaykh" },
		{ label: i18n.t("Luxor"), value: "Luxor" },
		{ label: i18n.t("Port Said"), value: "Port Said" },
		{ label: i18n.t("Rafah"), value: "Rafah" },
		{ label: i18n.t("Sohag"), value: "Sohag" },
		{ label: i18n.t("Suez"), value: "Suez" },
		{ label: i18n.t("Tanta"), value: "Tanta" },
		{ label: i18n.t("Al Sharqeyah"), value: "Al Sharqeyah" },
	],
	Gabon: [
		{ label: i18n.t("Gamba"), value: "Gamba" },
		{ label: i18n.t("Libreville"), value: "Libreville" },
		{ label: i18n.t("Mamagnia"), value: "Mamagnia" },
		{ label: i18n.t("Moanda"), value: "Moanda" },
		{ label: i18n.t("Port-Gentil"), value: "Port-Gentil" },
	],
	Georgia: [
		{ label: i18n.t("Gogolesubani"), value: "Gogolesubani" },
		{ label: i18n.t("Kutaisi"), value: "Kutaisi" },
		{ label: i18n.t("Lentekhi"), value: "Lentekhi" },
		{ label: i18n.t("Qazbegi"), value: "Qazbegi" },
		{ label: i18n.t("Samtredia"), value: "Samtredia" },
		{ label: i18n.t("Sukhumi"), value: "Sukhumi" },
		{ label: i18n.t("Tbilisi"), value: "Tbilisi" },
		{ label: i18n.t("ZemoAvchala"), value: "ZemoAvchala" },
		{ label: i18n.t("Zugdidi"), value: "Zugdidi" },
	],
	Ghana: [
		{ label: i18n.t("Accra"), value: "Accra" },
		{ label: i18n.t("Bawku"), value: "Bawku" },
		{ label: i18n.t("Berekum"), value: "Berekum" },
		{ label: i18n.t("Bolgatanga"), value: "Bolgatanga" },
		{ label: i18n.t("Home"), value: "Home" },
		{ label: i18n.t("Koforidua"), value: "Koforidua" },
		{ label: i18n.t("Kumasi"), value: "Kumasi" },
		{ label: i18n.t("Legon"), value: "Legon" },
		{ label: i18n.t("Mampong"), value: "Mampong" },
		{ label: i18n.t("Navrongo"), value: "Navrongo" },
		{ label: i18n.t("Sunyani"), value: "Sunyani" },
		{ label: i18n.t("Takoradi"), value: "Takoradi" },
		{ label: i18n.t("Tema"), value: "Tema" },
		{ label: i18n.t("Wa"), value: "Wa" },
		{ label: i18n.t("Winneba"), value: "Winneba" },
	],
	Greenland: [
		{ label: i18n.t("Aasiaat"), value: "Aasiaat" },
		{ label: i18n.t("Ilulissat"), value: "Ilulissat" },
		{ label: i18n.t("Kapisillit"), value: "Kapisillit" },
		{ label: i18n.t("Maniitsoq"), value: "Maniitsoq" },
		{ label: i18n.t("Narsaq"), value: "Narsaq" },
		{ label: i18n.t("Narsarsuaq"), value: "Narsarsuaq" },
		{ label: i18n.t("Nuuk"), value: "Nuuk" },
		{ label: i18n.t("Nuussuaq"), value: "Nuussuaq" },
		{ label: i18n.t("Paamiut"), value: "Paamiut" },
		{ label: i18n.t("Qaqortoq"), value: "Qaqortoq" },
		{ label: i18n.t("Qasigiannguit"), value: "Qasigiannguit" },
		{ label: i18n.t("Qeqertarsuaq"), value: "Qeqertarsuaq" },
		{ label: i18n.t("Qeqertat"), value: "Qeqertat" },
		{ label: i18n.t("Sisimiut"), value: "Sisimiut" },
		{ label: i18n.t("Tasiilaq"), value: "Tasiilaq" },
		{ label: i18n.t("Upernavik"), value: "Upernavik" },
	],
	Guinea: [
		{ label: i18n.t("Conakry"), value: "Conakry" },
		{ label: i18n.t("Dabola"), value: "Dabola" },
		{ label: i18n.t("Kalia"), value: "Kalia" },
		{ label: i18n.t("Kankan"), value: "Kankan" },
		{ label: i18n.t("Lola"), value: "Lola" },
		{ label: i18n.t("Mamou"), value: "Mamou" },
		{ label: i18n.t("Sangaredi"), value: "Sangaredi" },
	],
	Honduras: [
		{ label: i18n.t("Choloma"), value: "Choloma" },
		{ label: i18n.t("Comayagua"), value: "Comayagua" },
		{ label: i18n.t("Comayaguela"), value: "Comayaguela" },
		{ label: i18n.t("Coxen Hole"), value: "Hole" },
		{ label: i18n.t("Morazan"), value: "Morazan" },
		{ label: i18n.t("Nacaome"), value: "Nacaome" },
		{ label: i18n.t("Pinalejo"), value: "Pinalejo" },
		{ label: i18n.t("Piraera"), value: "Piraera" },
		{ label: i18n.t("Sula"), value: "Sula" },
		{ label: i18n.t("Tegucigalpa"), value: "Tegucigalpa" },
	],
	Iraq: [
		{ label: i18n.t("Al `Amarah"), value: "Al `Amarah" },
		{ label: i18n.t("Al Hillah"), value: "Al Hillah" },
		{ label: i18n.t("Baghdad"), value: "Baghdad" },
		{ label: i18n.t("Bahr"), value: "Bahr" },
		{ label: i18n.t("Basere"), value: "Basere" },
		{ label: i18n.t("Basra"), value: "Basra" },
		{ label: i18n.t("Erbil"), value: "Erbil" },
		{ label: i18n.t("Haji Hasan"), value: "Haji Hasan" },
		{ label: i18n.t("Hayat"), value: "Hayat" },
		{ label: i18n.t("Karkh"), value: "Karkh" },
		{ label: i18n.t("Kirkuk"), value: "Kirkuk" },
		{ label: i18n.t("Manawi"), value: "Manawi" },
		{ label: i18n.t("Mosul"), value: "Mosul" },
		{ label: i18n.t("Najaf"), value: "Najaf" },
		{ label: i18n.t("Sulaymaniyah"), value: "Sulaymaniyah" },
		{ label: i18n.t("Tikrit"), value: "Tikrit" },
	],
	Jamaica: [
		{ label: i18n.t("Kingston"), value: "Kingston" },
		{ label: i18n.t("Mandeville"), value: "Mandeville" },
		{ label: i18n.t("Moneague"), value: "Moneague" },
		{ label: i18n.t("Negril"), value: "Negril" },
		{ label: i18n.t("Portmore"), value: "Portmore" },
	],
	Kuwait: [
		{ label: i18n.t("Abraq Khaytan"), value: "Abraq Khaytan" },
		{ label: i18n.t("Ad Dasmah"), value: "Ad Dasmah" },
		{ label: i18n.t("Ad Dawhah"), value: "Ad Dawhah" },
		{ label: i18n.t("Al Ahmadi"), value: "Al Ahmadi" },
		{ label: i18n.t("Al Farwaniyah"), value: "Al Farwaniyah" },
		{ label: i18n.t("Al Shamiya"), value: "Al Shamiya" },
		{ label: i18n.t("Ar Rawdah"), value: "Ar Rawdah" },
		{ label: i18n.t("As Salimiyah"), value: "As Salimiyah" },
		{ label: i18n.t("Ash Shuaybah"), value: "Ash Shuaybah" },
		{ label: i18n.t("Ash Shuwaykh"), value: "Ash Shuwaykh" },
		{ label: i18n.t("Bayan"), value: "Bayan" },
		{ label: i18n.t("Hawalli"), value: "Hawalli" },
		{ label: i18n.t("Janub as Surrah"), value: "Janub as Surrah" },
		{ label: i18n.t("Kayfan"), value: "Kayfan" },
		{ label: i18n.t("Kuwait City"), value: "Kuwait City" },
		{ label: i18n.t("Salwa"), value: "Salwa" },
	],
	Lebanon: [
		{ label: i18n.t("Aaley"), value: "Aaley" },
		{ label: i18n.t("Adma"), value: "Adma" },
		{ label: i18n.t("Ashrafiye"), value: "Ashrafiye" },
		{ label: i18n.t("Baabda"), value: "Baabda" },
		{ label: i18n.t("Baalbek"), value: "Baalbek" },
		{ label: i18n.t("Beirut"), value: "Beirut" },
		{ label: i18n.t("Broummana"), value: "Broummana" },
		{ label: i18n.t("Bsalim"), value: "Bsalim" },
		{ label: i18n.t("Chekka"), value: "Chekka" },
		{ label: i18n.t("Dbaiye"), value: "Dbaiye" },
		{ label: i18n.t("Halba"), value: "Halba" },
		{ label: i18n.t("Hboub"), value: "Hboub" },
		{ label: i18n.t("Sarba"), value: "Sarba" },
		{ label: i18n.t("Sidon"), value: "Sidon" },
		{ label: i18n.t("Tripoli"), value: "Tripoli" },
		{ label: i18n.t("Yanar"), value: "Yanar" },
		{ label: i18n.t("Zgharta"), value: "Zgharta" },
	],
	Libya: [
		{ label: i18n.t("Benghazi"), value: "Benghazi" },
		{ label: i18n.t("Misratah"), value: "Misratah" },
		{ label: i18n.t("Sabha"), value: "Sabha" },
		{ label: i18n.t("Zliten"), value: "Zliten" },
	],
	Morocco: [
		{ label: i18n.t("Afourer"), value: "Afourer" },
		{ label: i18n.t("Agadir"), value: "Agadir" },
		{ label: i18n.t("Assa"), value: "Assa" },
		{ label: i18n.t("Benguerir"), value: "Benguerir" },
		{ label: i18n.t("Berrechid"), value: "Berrechid" },
		{ label: i18n.t("Casablanca"), value: "Casablanca" },
		{ label: i18n.t("Deroua"), value: "Deroua" },
		{ label: i18n.t("Erfoud"), value: "Erfoud" },
		{ label: i18n.t("Fes"), value: "Fes" },
		{ label: i18n.t("Kenitra"), value: "Kenitra" },
		{ label: i18n.t("Khemisset"), value: "Khemisset" },
		{ label: i18n.t("Khouribga"), value: "Khouribga" },
		{ label: i18n.t("Larache"), value: "Larache" },
		{ label: i18n.t("Mansour"), value: "Mansour" },
		{ label: i18n.t("Marrakesh"), value: "Marrakesh" },
		{ label: i18n.t("Mehediyah"), value: "Mehediyah" },
		{ label: i18n.t("Meknes"), value: "Meknes" },
		{ label: i18n.t("Mohammedia"), value: "Mohammedia" },
		{ label: i18n.t("Nador"), value: "Nador" },
		{ label: i18n.t("Ouazzane"), value: "Ouazzane" },
		{ label: i18n.t("Oujda"), value: "Oujda" },
		{ label: i18n.t("Rabat"), value: "Rabat" },
		{ label: i18n.t("Safi"), value: "Safi" },
		{ label: i18n.t("Sefrou"), value: "Sefrou" },
		{ label: i18n.t("Settat"), value: "Settat" },
		{ label: i18n.t("Skhirat"), value: "Skhirat" },
		{ label: i18n.t("Tahala"), value: "Tahala" },
		{ label: i18n.t("Tan-Tan"), value: "Tan-Tan" },
		{ label: i18n.t("Tangier"), value: "Tangier" },
		{ label: i18n.t("Tarfaya"), value: "Tarfaya" },
		{ label: i18n.t("Taza"), value: "Taza" },
		{ label: i18n.t("Temara"), value: "Temara" },
		{ label: i18n.t("Tiflet"), value: "Tiflet" },
		{ label: i18n.t("Tiznit"), value: "Tiznit" },
		{ label: i18n.t("Touissite"), value: "Touissite" },
	],
	Mozambique: [
		{ label: i18n.t("Beira"), value: "Beira" },
		{ label: i18n.t("Maputo"), value: "Maputo" },
		{ label: i18n.t("Matola"), value: "Matola" },
		{ label: i18n.t("Mozambique"), value: "Mozambique" },
		{ label: i18n.t("Nampula"), value: "Nampula" },
		{ label: i18n.t("Pemba"), value: "Pemba" },
		{ label: i18n.t("Quelimane"), value: "Quelimane" },
		{ label: i18n.t("Tete"), value: "Tete" },
	],
	Myanmar: [
		{ label: i18n.t("Hlaing"), value: "Hlaing" },
		{ label: i18n.t("Inya"), value: "Inya" },
		{ label: i18n.t("Kyauktada"), value: "Kyauktada" },
		{ label: i18n.t("Mandalay"), value: "Mandalay" },
		{ label: i18n.t("Wagan"), value: "Wagan" },
		{ label: i18n.t("Yangon"), value: "Yangon" },
	],
	Namibia: [
		{ label: i18n.t("Etunda"), value: "Etunda" },
		{ label: i18n.t("Grootfontein"), value: "Grootfontein" },
		{ label: i18n.t("Keetmanshoop"), value: "Keetmanshoop" },
		{ label: i18n.t("Mpapuka"), value: "Mpapuka" },
		{ label: i18n.t("Olympia"), value: "Olympia" },
		{ label: i18n.t("Ondangwa"), value: "Ondangwa" },
		{ label: i18n.t("Ongwediva"), value: "Ongwediva" },
		{ label: i18n.t("Oranjemund"), value: "Oranjemund" },
		{ label: i18n.t("Oshakati"), value: "Oshakati" },
		{ label: i18n.t("Otjiwarongo"), value: "Otjiwarongo" },
		{ label: i18n.t("Outapi"), value: "Outapi" },
		{ label: i18n.t("Swakopmund"), value: "Swakopmund" },
		{ label: i18n.t("Tsumeb"), value: "Tsumeb" },
		{ label: i18n.t("Windhoek"), value: "Windhoek" },
	],
	Nepal: [
		{ label: i18n.t("Bharatpur"), value: "Bharatpur" },
		{ label: i18n.t("Jawlakhel"), value: "Jawlakhel" },
		{ label: i18n.t("Kathmandu"), value: "Kathmandu" },
		{ label: i18n.t("Lumbini"), value: "Lumbini" },
		{ label: i18n.t("Palpa"), value: "Palpa" },
		{ label: i18n.t("Patan"), value: "Patan" },
	],
	Nicaragua: [
		{ label: i18n.t("Bluefields"), value: "Bluefields" },
		{ label: i18n.t("Chinandega"), value: "Chinandega" },
		{ label: i18n.t("Esteli"), value: "Esteli" },
		{ label: i18n.t("Granada"), value: "Granada" },
		{ label: i18n.t("Jinotega"), value: "Jinotega" },
		{ label: i18n.t("Managua"), value: "Managua" },
		{ label: i18n.t("Masaya"), value: "Masaya" },
		{ label: i18n.t("Matagalpa"), value: "Matagalpa" },
		{ label: i18n.t("Ocotal"), value: "Ocotal" },
		{ label: i18n.t("Rivas"), value: "Rivas" },
	],
	Oman: [
		{ label: i18n.t("Al Sohar"), value: "Al Sohar" },
		{ label: i18n.t("Muscat"), value: "Muscat" },
		{ label: i18n.t("Nizwa"), value: "Nizwa" },
		{ label: i18n.t("Ruwi"), value: "Ruwi" },
		{ label: i18n.t("Saham"), value: "Saham" },
		{ label: i18n.t("Salalah"), value: "Salalah" },
		{ label: i18n.t("Samad"), value: "Samad" },
	],
	Palestine: [
		{ label: i18n.t("Al Mawasi"), value: "Al Mawasi" },
		{ label: i18n.t("Bethlehem"), value: "Bethlehem" },
		{ label: i18n.t("Gaza"), value: "Gaza" },
		{ label: i18n.t("Hebron"), value: "Hebron" },
		{ label: i18n.t("Jenin"), value: "Jenin" },
		{ label: i18n.t("Jericho"), value: "Jericho" },
		{ label: i18n.t("Nablus"), value: "Nablus" },
		{ label: i18n.t("Ramallah"), value: "Ramallah" },
	],
	Senegal: [
		{ label: i18n.t("Boussinki"), value: "Boussinki" },
		{ label: i18n.t("Camberene"), value: "Camberene" },
		{ label: i18n.t("Dakar"), value: "Dakar" },
		{ label: i18n.t("Dodji"), value: "Dodji" },
		{ label: i18n.t("Guediawaye"), value: "Guediawaye" },
		{ label: i18n.t("Kaolack"), value: "Kaolack" },
		{ label: i18n.t("Kedougou"), value: "Kedougou" },
		{ label: i18n.t("Louga"), value: "Louga" },
		{ label: i18n.t("Saint-Louis"), value: "Louis" },
		{ label: i18n.t("Sama"), value: "Sama" },
		{ label: i18n.t("Tanaf"), value: "Tanaf" },
	],
	Sudan: [
		{ label: i18n.t("Kassala"), value: "Kassala" },
		{ label: i18n.t("Khartoum"), value: "Khartoum" },
		{ label: i18n.t("Nyala"), value: "Nyala" },
		{ label: i18n.t("Shendi"), value: "Shendi" },
		{ label: i18n.t("Thabit"), value: "Thabit" },
		{ label: i18n.t("Umm Durman"), value: "Umm Durman" },
	],
	Tunisia: [
		{ label: i18n.t("Ariana"), value: "Ariana" },
		{ label: i18n.t("Beja"), value: "Beja" },
		{ label: i18n.t("Gafsa"), value: "Gafsa" },
		{ label: i18n.t("Hammamet"), value: "Hammamet" },
		{ label: i18n.t("Le Bardo"), value: "Le Bardo" },
		{ label: i18n.t("Manouba"), value: "Manouba" },
		{ label: i18n.t("Monastir"), value: "Monastir" },
		{ label: i18n.t("Rades"), value: "Rades" },
		{ label: i18n.t("Sfax"), value: "Sfax" },
		{ label: i18n.t("Sidi Bouzid"), value: "Sidi Bouzid" },
		{ label: i18n.t("Sousse"), value: "Sousse" },
		{ label: i18n.t("Tunis"), value: "Tunis" },
	],
	"United Arab Emirates": [
		{ label: i18n.t("Abu Dhabi"), value: "Abu Dhabi" },
		{ label: i18n.t("Al Ain"), value: "Al Ain" },
		{ label: i18n.t("Al Khan"), value: "Al Khan" },
		{ label: i18n.t("Ar Ruways"), value: "Ar Ruways" },
		{ label: i18n.t("As Satwah"), value: "As Satwah" },
		{ label: i18n.t("Dayrah"), value: "Dayrah" },
		{ label: i18n.t("Dubai"), value: "Dubai" },
		{ label: i18n.t("Fujairah"), value: "Fujairah" },
		{ label: i18n.t("Ras alKhaimah"), value: "Ras alKhaimah" },
		{ label: i18n.t("Sharjah"), value: "Sharjah" },
	],
};

export const $mobileCodes = [
	{
		label: "+93",
		value: "93",
	},
	{
		label: "+358",
		value: "358",
	},
	{
		label: "+355",
		value: "355",
	},
	{
		label: "+213",
		value: "213",
	},
	{
		label: "+1684",
		value: "1684",
	},
	{
		label: "+376",
		value: "376",
	},
	{
		label: "+244",
		value: "244",
	},
	{
		label: "+1264",
		value: "1264",
	},
	{
		label: "+1268",
		value: "1268",
	},
	{
		label: "+54",
		value: "54",
	},
	{
		label: "+374",
		value: "374",
	},
	{
		label: "+297",
		value: "297",
	},
	{
		label: "+43",
		value: "43",
	},
	{
		label: "+994",
		value: "994",
	},
	{
		label: "+1242",
		value: "1242",
	},
	{
		label: "+973",
		value: "973",
	},
	{
		label: "+880",
		value: "880",
	},
	{
		label: "+1246",
		value: "1246",
	},
	{
		label: "+375",
		value: "375",
	},
	{
		label: "+32",
		value: "32",
	},
	{
		label: "+501",
		value: "501",
	},
	{
		label: "+229",
		value: "229",
	},
	{
		label: "+1441",
		value: "1441",
	},
	{
		label: "+975",
		value: "975",
	},
	{
		label: "+591",
		value: "591",
	},
	{
		label: "+387",
		value: "387",
	},
	{
		label: "+267",
		value: "267",
	},
	{
		label: "+55",
		value: "55",
	},
	{
		label: "+246",
		value: "246",
	},
	{
		label: "+673",
		value: "673",
	},
	{
		label: "+359",
		value: "359",
	},
	{
		label: "+226",
		value: "226",
	},
	{
		label: "+257",
		value: "257",
	},
	{
		label: "+855",
		value: "855",
	},
	{
		label: "+237",
		value: "237",
	},
	{
		label: "+1",
		value: "1",
	},
	{
		label: "+238",
		value: "238",
	},
	{
		label: "+ 345",
		value: " 345",
	},
	{
		label: "+236",
		value: "236",
	},
	{
		label: "+235",
		value: "235",
	},
	{
		label: "+56",
		value: "56",
	},
	{
		label: "+86",
		value: "86",
	},
	{
		label: "+61",
		value: "61",
	},
	{
		label: "+57",
		value: "57",
	},
	{
		label: "+269",
		value: "269",
	},
	{
		label: "+242",
		value: "242",
	},
	{
		label: "+243",
		value: "243",
	},
	{
		label: "+682",
		value: "682",
	},
	{
		label: "+506",
		value: "506",
	},
	{
		label: "+225",
		value: "225",
	},
	{
		label: "+385",
		value: "385",
	},
	{
		label: "+53",
		value: "53",
	},
	{
		label: "+357",
		value: "357",
	},
	{
		label: "+420",
		value: "420",
	},
	{
		label: "+45",
		value: "45",
	},
	{
		label: "+253",
		value: "253",
	},
	{
		label: "+1767",
		value: "1767",
	},
	{
		label: "+1849",
		value: "1849",
	},
	{
		label: "+593",
		value: "593",
	},
	{
		label: "+20",
		value: "20",
	},
	{
		label: "+503",
		value: "503",
	},
	{
		label: "+240",
		value: "240",
	},
	{
		label: "+291",
		value: "291",
	},
	{
		label: "+372",
		value: "372",
	},
	{
		label: "+251",
		value: "251",
	},
	{
		label: "+500",
		value: "500",
	},
	{
		label: "+298",
		value: "298",
	},
	{
		label: "+679",
		value: "679",
	},
	{
		label: "+33",
		value: "33",
	},
	{
		label: "+594",
		value: "594",
	},
	{
		label: "+689",
		value: "689",
	},
	{
		label: "+241",
		value: "241",
	},
	{
		label: "+220",
		value: "220",
	},
	{
		label: "+995",
		value: "995",
	},
	{
		label: "+49",
		value: "49",
	},
	{
		label: "+233",
		value: "233",
	},
	{
		label: "+350",
		value: "350",
	},
	{
		label: "+30",
		value: "30",
	},
	{
		label: "+299",
		value: "299",
	},
	{
		label: "+1473",
		value: "1473",
	},
	{
		label: "+590",
		value: "590",
	},
	{
		label: "+1671",
		value: "1671",
	},
	{
		label: "+502",
		value: "502",
	},
	{
		label: "+224",
		value: "224",
	},
	{
		label: "+245",
		value: "245",
	},
	{
		label: "+509",
		value: "509",
	},
	{
		label: "+379",
		value: "379",
	},
	{
		label: "+504",
		value: "504",
	},
	{
		label: "+852",
		value: "852",
	},
	{
		label: "+36",
		value: "36",
	},
	{
		label: "+354",
		value: "354",
	},
	{
		label: "+91",
		value: "91",
	},
	{
		label: "+62",
		value: "62",
	},
	{
		label: "+98",
		value: "98",
	},
	{
		label: "+964",
		value: "964",
	},
	{
		label: "+353",
		value: "353",
	},
	{
		label: "+972",
		value: "972",
	},
	{
		label: "+39",
		value: "39",
	},
	{
		label: "+1876",
		value: "1876",
	},
	{
		label: "+81",
		value: "81",
	},
	{
		label: "+962",
		value: "962",
	},
	{
		label: "+77",
		value: "77",
	},
	{
		label: "+254",
		value: "254",
	},
	{
		label: "+686",
		value: "686",
	},
	{
		label: "+850",
		value: "850",
	},
	{
		label: "+82",
		value: "82",
	},
	{
		label: "+965",
		value: "965",
	},
	{
		label: "+996",
		value: "996",
	},
	{
		label: "+856",
		value: "856",
	},
	{
		label: "+371",
		value: "371",
	},
	{
		label: "+961",
		value: "961",
	},
	{
		label: "+266",
		value: "266",
	},
	{
		label: "+231",
		value: "231",
	},
	{
		label: "+218",
		value: "218",
	},
	{
		label: "+423",
		value: "423",
	},
	{
		label: "+370",
		value: "370",
	},
	{
		label: "+352",
		value: "352",
	},
	{
		label: "+853",
		value: "853",
	},
	{
		label: "+389",
		value: "389",
	},
	{
		label: "+261",
		value: "261",
	},
	{
		label: "+265",
		value: "265",
	},
	{
		label: "+60",
		value: "60",
	},
	{
		label: "+960",
		value: "960",
	},
	{
		label: "+223",
		value: "223",
	},
	{
		label: "+356",
		value: "356",
	},
	{
		label: "+692",
		value: "692",
	},
	{
		label: "+596",
		value: "596",
	},
	{
		label: "+222",
		value: "222",
	},
	{
		label: "+230",
		value: "230",
	},
	{
		label: "+52",
		value: "52",
	},
	{
		label: "+691",
		value: "691",
	},
	{
		label: "+373",
		value: "373",
	},
	{
		label: "+377",
		value: "377",
	},
	{
		label: "+976",
		value: "976",
	},
	{
		label: "+382",
		value: "382",
	},
	{
		label: "+1664",
		value: "1664",
	},
	{
		label: "+212",
		value: "212",
	},
	{
		label: "+258",
		value: "258",
	},
	{
		label: "+95",
		value: "95",
	},
	{
		label: "+264",
		value: "264",
	},
	{
		label: "+674",
		value: "674",
	},
	{
		label: "+977",
		value: "977",
	},
	{
		label: "+31",
		value: "31",
	},
	{
		label: "+599",
		value: "599",
	},
	{
		label: "+687",
		value: "687",
	},
	{
		label: "+64",
		value: "64",
	},
	{
		label: "+505",
		value: "505",
	},
	{
		label: "+227",
		value: "227",
	},
	{
		label: "+234",
		value: "234",
	},
	{
		label: "+683",
		value: "683",
	},
	{
		label: "+672",
		value: "672",
	},
	{
		label: "+1670",
		value: "1670",
	},
	{
		label: "+968",
		value: "968",
	},
	{
		label: "+92",
		value: "92",
	},
	{
		label: "+680",
		value: "680",
	},
	{
		label: "+970",
		value: "970",
	},
	{
		label: "+507",
		value: "507",
	},
	{
		label: "+675",
		value: "675",
	},
	{
		label: "+595",
		value: "595",
	},
	{
		label: "+51",
		value: "51",
	},
	{
		label: "+63",
		value: "63",
	},
	{
		label: "+872",
		value: "872",
	},
	{
		label: "+48",
		value: "48",
	},
	{
		label: "+351",
		value: "351",
	},
	{
		label: "+1939",
		value: "1939",
	},
	{
		label: "+974",
		value: "974",
	},
	{
		label: "+40",
		value: "40",
	},
	{
		label: "+7",
		value: "7",
	},
	{
		label: "+250",
		value: "250",
	},
	{
		label: "+262",
		value: "262",
	},
	{
		label: "+290",
		value: "290",
	},
	{
		label: "+1869",
		value: "1869",
	},
	{
		label: "+1758",
		value: "1758",
	},
	{
		label: "+508",
		value: "508",
	},
	{
		label: "+1784",
		value: "1784",
	},
	{
		label: "+685",
		value: "685",
	},
	{
		label: "+378",
		value: "378",
	},
	{
		label: "+239",
		value: "239",
	},
	{
		label: "+966",
		value: "966",
	},
	{
		label: "+221",
		value: "221",
	},
	{
		label: "+381",
		value: "381",
	},
	{
		label: "+248",
		value: "248",
	},
	{
		label: "+232",
		value: "232",
	},
	{
		label: "+65",
		value: "65",
	},
	{
		label: "+421",
		value: "421",
	},
	{
		label: "+386",
		value: "386",
	},
	{
		label: "+677",
		value: "677",
	},
	{
		label: "+252",
		value: "252",
	},
	{
		label: "+27",
		value: "27",
	},
	{
		label: "+211",
		value: "211",
	},
	{
		label: "+34",
		value: "34",
	},
	{
		label: "+94",
		value: "94",
	},
	{
		label: "+249",
		value: "249",
	},
	{
		label: "+597",
		value: "597",
	},
	{
		label: "+47",
		value: "47",
	},
	{
		label: "+268",
		value: "268",
	},
	{
		label: "+46",
		value: "46",
	},
	{
		label: "+41",
		value: "41",
	},
	{
		label: "+963",
		value: "963",
	},
	{
		label: "+886",
		value: "886",
	},
	{
		label: "+992",
		value: "992",
	},
	{
		label: "+255",
		value: "255",
	},
	{
		label: "+66",
		value: "66",
	},
	{
		label: "+670",
		value: "670",
	},
	{
		label: "+228",
		value: "228",
	},
	{
		label: "+690",
		value: "690",
	},
	{
		label: "+676",
		value: "676",
	},
	{
		label: "+1868",
		value: "1868",
	},
	{
		label: "+216",
		value: "216",
	},
	{
		label: "+90",
		value: "90",
	},
	{
		label: "+993",
		value: "993",
	},
	{
		label: "+1649",
		value: "1649",
	},
	{
		label: "+688",
		value: "688",
	},
	{
		label: "+256",
		value: "256",
	},
	{
		label: "+380",
		value: "380",
	},
	{
		label: "+971",
		value: "971",
	},
	{
		label: "+44",
		value: "44",
	},
	{
		label: "+598",
		value: "598",
	},
	{
		label: "+998",
		value: "998",
	},
	{
		label: "+678",
		value: "678",
	},
	{
		label: "+58",
		value: "58",
	},
	{
		label: "+84",
		value: "84",
	},
	{
		label: "+1284",
		value: "1284",
	},
	{
		label: "+1340",
		value: "1340",
	},
	{
		label: "+681",
		value: "681",
	},
	{
		label: "+967",
		value: "967",
	},
	{
		label: "+260",
		value: "260",
	},
	{
		label: "+263",
		value: "263",
	},
];

export const $status = [
	{ text: i18n.t("Inactive"), value: "0" },
	{ text: i18n.t("Active"), value: "1" },
];

export const $genders = [
	{ text: i18n.t("Male"), value: "0" },
	{ text: i18n.t("Female"), value: "1" },
];

export const $languages = [
	{ label: i18n.t("Arabic"), value: "0" },
	{ label: i18n.t("English"), value: "1" },
];

export const $layouts = [
	{ label: i18n.t("A4 landscape"), value: "0" },
	{ label: i18n.t("A4 portrait"), value: "1" },
	{ label: i18n.t("Letter landscape"), value: "2" },
	{ label: i18n.t("Letter portrait"), value: "3" },
	{ label: i18n.t("A3 landscape"), value: "4" },
	{ label: i18n.t("A3 portrait"), value: "5" },
];
